#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-protobuf-soname15
Version  : 3.5.1
Release  : 5
URL      : https://github.com/google/protobuf/archive/v3.5.1.tar.gz
Source0  : https://github.com/google/protobuf/archive/v3.5.1.tar.gz
Summary  : Google's Data Interchange Format
Group    : Development/Tools
License  : BSD-3-Clause
Requires: compat-protobuf-soname15-lib = %{version}-%{release}
Requires: compat-protobuf-soname15-license = %{version}-%{release}
Requires: setuptools
Requires: six
BuildRequires : setuptools
BuildRequires : six
BuildRequires : zlib-dev
# Suppress generation of debuginfo
%global debug_package %{nil}

%description
This is the 'v2' C++ implementation for python proto2.
It is active when:
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2

%package lib
Summary: lib components for the compat-protobuf-soname15 package.
Group: Libraries
Requires: compat-protobuf-soname15-license = %{version}-%{release}

%description lib
lib components for the compat-protobuf-soname15 package.


%package license
Summary: license components for the compat-protobuf-soname15 package.
Group: Default

%description license
license components for the compat-protobuf-soname15 package.


%prep
%setup -q -n protobuf-3.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568064190
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1568064190
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-protobuf-soname15
cp LICENSE %{buildroot}/usr/share/package-licenses/compat-protobuf-soname15/LICENSE
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/bin/protoc
rm -f %{buildroot}/usr/include/google/protobuf/any.h
rm -f %{buildroot}/usr/include/google/protobuf/any.pb.h
rm -f %{buildroot}/usr/include/google/protobuf/any.proto
rm -f %{buildroot}/usr/include/google/protobuf/api.pb.h
rm -f %{buildroot}/usr/include/google/protobuf/api.proto
rm -f %{buildroot}/usr/include/google/protobuf/arena.h
rm -f %{buildroot}/usr/include/google/protobuf/arena_impl.h
rm -f %{buildroot}/usr/include/google/protobuf/arenastring.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/code_generator.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/command_line_interface.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/cpp/cpp_generator.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/csharp/csharp_generator.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/csharp/csharp_names.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/importer.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/java/java_generator.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/java/java_names.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/javanano/javanano_generator.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/js/js_generator.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/js/well_known_types_embed.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/objectivec/objectivec_generator.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/objectivec/objectivec_helpers.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/parser.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/php/php_generator.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/plugin.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/plugin.pb.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/plugin.proto
rm -f %{buildroot}/usr/include/google/protobuf/compiler/python/python_generator.h
rm -f %{buildroot}/usr/include/google/protobuf/compiler/ruby/ruby_generator.h
rm -f %{buildroot}/usr/include/google/protobuf/descriptor.h
rm -f %{buildroot}/usr/include/google/protobuf/descriptor.pb.h
rm -f %{buildroot}/usr/include/google/protobuf/descriptor.proto
rm -f %{buildroot}/usr/include/google/protobuf/descriptor_database.h
rm -f %{buildroot}/usr/include/google/protobuf/duration.pb.h
rm -f %{buildroot}/usr/include/google/protobuf/duration.proto
rm -f %{buildroot}/usr/include/google/protobuf/dynamic_message.h
rm -f %{buildroot}/usr/include/google/protobuf/empty.pb.h
rm -f %{buildroot}/usr/include/google/protobuf/empty.proto
rm -f %{buildroot}/usr/include/google/protobuf/extension_set.h
rm -f %{buildroot}/usr/include/google/protobuf/field_mask.pb.h
rm -f %{buildroot}/usr/include/google/protobuf/field_mask.proto
rm -f %{buildroot}/usr/include/google/protobuf/generated_enum_reflection.h
rm -f %{buildroot}/usr/include/google/protobuf/generated_enum_util.h
rm -f %{buildroot}/usr/include/google/protobuf/generated_message_reflection.h
rm -f %{buildroot}/usr/include/google/protobuf/generated_message_table_driven.h
rm -f %{buildroot}/usr/include/google/protobuf/generated_message_util.h
rm -f %{buildroot}/usr/include/google/protobuf/has_bits.h
rm -f %{buildroot}/usr/include/google/protobuf/io/coded_stream.h
rm -f %{buildroot}/usr/include/google/protobuf/io/gzip_stream.h
rm -f %{buildroot}/usr/include/google/protobuf/io/printer.h
rm -f %{buildroot}/usr/include/google/protobuf/io/strtod.h
rm -f %{buildroot}/usr/include/google/protobuf/io/tokenizer.h
rm -f %{buildroot}/usr/include/google/protobuf/io/zero_copy_stream.h
rm -f %{buildroot}/usr/include/google/protobuf/io/zero_copy_stream_impl.h
rm -f %{buildroot}/usr/include/google/protobuf/io/zero_copy_stream_impl_lite.h
rm -f %{buildroot}/usr/include/google/protobuf/map.h
rm -f %{buildroot}/usr/include/google/protobuf/map_entry.h
rm -f %{buildroot}/usr/include/google/protobuf/map_entry_lite.h
rm -f %{buildroot}/usr/include/google/protobuf/map_field.h
rm -f %{buildroot}/usr/include/google/protobuf/map_field_inl.h
rm -f %{buildroot}/usr/include/google/protobuf/map_field_lite.h
rm -f %{buildroot}/usr/include/google/protobuf/map_type_handler.h
rm -f %{buildroot}/usr/include/google/protobuf/message.h
rm -f %{buildroot}/usr/include/google/protobuf/message_lite.h
rm -f %{buildroot}/usr/include/google/protobuf/metadata.h
rm -f %{buildroot}/usr/include/google/protobuf/metadata_lite.h
rm -f %{buildroot}/usr/include/google/protobuf/reflection.h
rm -f %{buildroot}/usr/include/google/protobuf/reflection_ops.h
rm -f %{buildroot}/usr/include/google/protobuf/repeated_field.h
rm -f %{buildroot}/usr/include/google/protobuf/service.h
rm -f %{buildroot}/usr/include/google/protobuf/source_context.pb.h
rm -f %{buildroot}/usr/include/google/protobuf/source_context.proto
rm -f %{buildroot}/usr/include/google/protobuf/struct.pb.h
rm -f %{buildroot}/usr/include/google/protobuf/struct.proto
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomic_sequence_num.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomicops.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomicops_internals_arm64_gcc.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomicops_internals_arm_gcc.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomicops_internals_arm_qnx.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomicops_internals_generic_c11_atomic.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomicops_internals_generic_gcc.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomicops_internals_mips_gcc.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomicops_internals_power.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomicops_internals_ppc_gcc.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomicops_internals_solaris.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomicops_internals_tsan.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomicops_internals_x86_gcc.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/atomicops_internals_x86_msvc.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/bytestream.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/callback.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/casts.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/common.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/fastmem.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/hash.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/logging.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/macros.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/mutex.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/once.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/platform_macros.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/port.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/scoped_ptr.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/shared_ptr.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/singleton.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/status.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/stl_util.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/stringpiece.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/template_util.h
rm -f %{buildroot}/usr/include/google/protobuf/stubs/type_traits.h
rm -f %{buildroot}/usr/include/google/protobuf/text_format.h
rm -f %{buildroot}/usr/include/google/protobuf/timestamp.pb.h
rm -f %{buildroot}/usr/include/google/protobuf/timestamp.proto
rm -f %{buildroot}/usr/include/google/protobuf/type.pb.h
rm -f %{buildroot}/usr/include/google/protobuf/type.proto
rm -f %{buildroot}/usr/include/google/protobuf/unknown_field_set.h
rm -f %{buildroot}/usr/include/google/protobuf/util/delimited_message_util.h
rm -f %{buildroot}/usr/include/google/protobuf/util/field_comparator.h
rm -f %{buildroot}/usr/include/google/protobuf/util/field_mask_util.h
rm -f %{buildroot}/usr/include/google/protobuf/util/json_util.h
rm -f %{buildroot}/usr/include/google/protobuf/util/message_differencer.h
rm -f %{buildroot}/usr/include/google/protobuf/util/time_util.h
rm -f %{buildroot}/usr/include/google/protobuf/util/type_resolver.h
rm -f %{buildroot}/usr/include/google/protobuf/util/type_resolver_util.h
rm -f %{buildroot}/usr/include/google/protobuf/wire_format.h
rm -f %{buildroot}/usr/include/google/protobuf/wire_format_lite.h
rm -f %{buildroot}/usr/include/google/protobuf/wire_format_lite_inl.h
rm -f %{buildroot}/usr/include/google/protobuf/wrappers.pb.h
rm -f %{buildroot}/usr/include/google/protobuf/wrappers.proto
rm -f %{buildroot}/usr/lib64/libprotobuf-lite.so
rm -f %{buildroot}/usr/lib64/libprotobuf.so
rm -f %{buildroot}/usr/lib64/libprotoc.so
rm -f %{buildroot}/usr/lib64/pkgconfig/protobuf-lite.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/protobuf.pc

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libprotobuf-lite.so.15
/usr/lib64/libprotobuf-lite.so.15.0.1
/usr/lib64/libprotobuf.so.15
/usr/lib64/libprotobuf.so.15.0.1
/usr/lib64/libprotoc.so.15
/usr/lib64/libprotoc.so.15.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-protobuf-soname15/LICENSE
